#!/bin/bash
ls -amp | sort -d  #The command lists all the files and directories in the current directory, separated by commas. It also includes hidden files and directories that start with a dot (.). The output is sorted alphabetically, except for directories . and … which are listed at the beginning. Digits come before letters.
